### ISSUE TITLE
Review imports to make proper use of /es or /lib folders

### ISSUE THREAD

**Issue by TestardR** [Amsterdam/matomo-tracker#303] opened 2020-10-16 11:26 UTC
**Describe the bug**
On EI11, all javascript files have to be converted to ES5 to work properly. The matomo team offers /es (in ES6) and /lib (in ES5) to match this need. However, in matomo-tracker-react/lib/instance.js, require("@datapunt/matomo-tracker-js") does not explicitly target the lib folder. As such, this import defaults to the /es, which make apps on EI11 crash.

I fixed this bug writing explicitly require("@datapunt/matomo-tracker-js/lib").

**To Reproduce**
I created a simple repo:
https://github.com/TestardR/matomo-EI11-bug
1. yarn install
2. yarn start
3. Open EI11 and Firefox/Chrome to compare

**Expected behavior**
It should show the classic CRA landing page.

**Screenshots**
![Screenshot 2020-10-16 at 13 24 23 (3)](https://user-images.githubusercontent.com/40339476/96253014-25a40180-0fb3-11eb-92df-ae4b5a8038ff.png)

SCRIPT1002: Syntax error. As you can see, it clearly points to ES6 javascript.
![Screenshot 2020-10-16 at 13 27 53](https://user-images.githubusercontent.com/40339476/96253205-7b78a980-0fb3-11eb-87f3-5b73e73614ef.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser EI
 - Version 11

**Comment by jonkoops** [comment] 2020-10-20 10:33
Hi @TestardR, thanks for opening this issue. First off, thank you for creating a repo to help us reproduce the problem this helps a lot in finding and resolving issues.

To support modern browsers and tooling better we include both an ES2015 (with ES modules) version as well as an ES5 (with CommonJS modules). We make use of the `module` field in the package file to explicitly allow modern tooling to make use of the ESM version.

By default `create-react-app` will use the ESM version wherever possible, which means that during development you will get an ES2015 version of the code. Naturally this does not work well together with older browsers such as Internet Explorer, as they do not support this modern syntax.

To resolve this problem `create-react-app` will transform this ES2015 syntax to ES5 in a **production** build. You can verify this by building your application and serving it locally:

```sh
yarn build && npx http-server build/
```

If you open the address provided by the server you will see that it will actually not produce any syntax errors in Internet Explorer. It will however produce several exceptions that are related to missing APIs such as `Object.assign` and `Object.entries` for which you will have to add the correct polyfills.

As mentioned in the `create-react-app` [documentation](https://create-react-app.dev/docs/supported-browsers-features#supported-browsers) you will have to add the [react-app-polyfill](https://github.com/facebook/create-react-app/blob/master/packages/react-app-polyfill/README.md) package to your application to support Internet Explorer 11. To do so install the package and add the following line to the top of `src/index.js`:

```js
// This must be the first line in src/index.js
import 'react-app-polyfill/ie11';
```

This will take care of the basic polyfills that are needed by React and some of the ones needed for `matomo-tracker`. For the polyfills that are not included here I would recommend that you use [core-js](https://github.com/zloirock/core-js) to provide the ones you need. For example since we need a polyfill for `Object.entries` you will have to include a polyfill as follows:

```js
// This must be the first line in src/index.js
import 'react-app-polyfill/ie11'
import 'core-js/modules/es.object.entries'
``` 

I hope this answers your question, if not feel free to drop me a line below.

**Closed by jonkoops** 2020-10-20 10:33 UTC
Labels: question
