### ISSUE TITLE
Use matomo tracker in class components

### ISSUE THREAD

**Issue by gianpo86** [Amsterdam/matomo-tracker#181] opened 2020-07-15 07:26 UTC
**Is your feature request related to a problem? Please describe.**
In our app there are still a lot of class components. How should I use The tracker in non-functional components which do not support hooks?

**Describe the solution you'd like**
A HOC or similar for the matomo wrapper

**Describe alternatives you've considered**
A documented workaround to use the current code in class components

**Comment by jonkoops** [comment] 2020-07-15 10:35
I am closing this issue as it is a duplicate of https://github.com/Amsterdam/matomo-tracker/issues/162. As mentioned we have no plans to implement a solution for class based components. If you do need to use Matomo in your class components we recommend using [matomo-tracker-js](https://github.com/Amsterdam/matomo-tracker/tree/master/packages/js) directly.

**Closed by jonkoops** 2020-07-15 10:35 UTC
Labels: duplicate, enhancement
